// Code generated by MockGen. DO NOT EDIT.
// Source: E:\tushartemplategin\pkg\interfaces\logger.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	interfaces "tushartemplategin/pkg/interfaces"

	gomock "github.com/golang/mock/gomock"
)

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Debug mocks base method.
func (m *MockLogger) Debug(ctx context.Context, msg string, fields interfaces.Fields) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Debug", ctx, msg, fields)
}

// Debug indicates an expected call of Debug.
func (mr *MockLoggerMockRecorder) Debug(ctx, msg, fields interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockLogger)(nil).Debug), ctx, msg, fields)
}

// Error mocks base method.
func (m *MockLogger) Error(ctx context.Context, msg string, fields interfaces.Fields) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Error", ctx, msg, fields)
}

// Error indicates an expected call of Error.
func (mr *MockLoggerMockRecorder) Error(ctx, msg, fields interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockLogger)(nil).Error), ctx, msg, fields)
}

// Fatal mocks base method.
func (m *MockLogger) Fatal(ctx context.Context, msg string, err error, fields interfaces.Fields) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Fatal", ctx, msg, err, fields)
}

// Fatal indicates an expected call of Fatal.
func (mr *MockLoggerMockRecorder) Fatal(ctx, msg, err, fields interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fatal", reflect.TypeOf((*MockLogger)(nil).Fatal), ctx, msg, err, fields)
}

// Info mocks base method.
func (m *MockLogger) Info(ctx context.Context, msg string, fields interfaces.Fields) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Info", ctx, msg, fields)
}

// Info indicates an expected call of Info.
func (mr *MockLoggerMockRecorder) Info(ctx, msg, fields interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockLogger)(nil).Info), ctx, msg, fields)
}

// Warn mocks base method.
func (m *MockLogger) Warn(ctx context.Context, msg string, fields interfaces.Fields) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Warn", ctx, msg, fields)
}

// Warn indicates an expected call of Warn.
func (mr *MockLoggerMockRecorder) Warn(ctx, msg, fields interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockLogger)(nil).Warn), ctx, msg, fields)
}
