server:
  port: ":8080"
  mode: "debug"

log:
  level: "info"
  format: "json"
  output: "stdout"
  filePath: "./logs"
  maxSize: 100
  maxBackup: 3
  maxAge: 0        # Disabled - no age-based deletion
  compress: true
  addCaller: true
  addStack: false

database:
  type: "postgres"  # Supported types: postgres, sqlite, mysql
  postgres:
    host: "localhost"
    port: 5432
    name: "tushar_db"
    username: "postgres"
    password: "password"
    sslMode: "disable"
    maxOpenConns: 25
    maxIdleConns: 5
    connMaxLifetime: "5m"
    connMaxIdleTime: "1m"
    timeout: "30s"
    # Production settings
    maxRetries: 3
    retryDelay: "1s"
    healthCheckInterval: "30s"